### ISSUE TITLE
No provider for Store! after upgrade to Angular 2.3.1

### ISSUE THREAD

**Issue by karlhaas** [ngrx/store#298]
Our application works with aot compilation but after upgrading Angular to version 2.3.1 we get the following error:

```
Error: No provider for Store!
    at NoProviderError.BaseError [as constructor] (http://localhost:5555/js/app.js?1482251644363:84342:29) [angular]
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:5555/js/app.js?1482251644363:82208:18) [angular]
    at new NoProviderError (http://localhost:5555/js/app.js?1482251644363:82225:18) [angular]
    at ReflectiveInjector_._throwOrNull (http://localhost:5555/js/app.js?1482251644363:82095:19) [angular]
    at ReflectiveInjector_._getByKeyDefault (http://localhost:5555/js/app.js?1482251644363:82119:25) [angular]
    at ReflectiveInjector_._getByKey (http://localhost:5555/js/app.js?1482251644363:82088:25) [angular]
    at ReflectiveInjector_.get (http://localhost:5555/js/app.js?1482251644363:81901:23) [angular]
    at AppModuleInjector.createInternal (http://localhost:5555/js/app.js?1482251644363:86934:91) [angular]
    at AppModuleInjector.NgModuleInjector.create (http://localhost:5555/js/app.js?1482251644363:77012:32) [angular]
    at NgModuleFactory.create (http://localhost:5555/js/app.js?1482251644363:76995:20) [angular]
    at http://localhost:5555/js/app.js?1482251644363:75220:44 [angular]
    at Object.onInvoke (http://localhost:5555/js/app.js?1482251644363:80157:33) [angular]
```

Changes between working and not working version:
```
   "devDependencies": {
-    "@angular/compiler-cli": "2.2.4",
-    "@angular/platform-server": "2.2.4",
+    "@angular/compiler-cli": "2.3.1",
+    "@angular/platform-server": "2.3.1",
-    "codelyzer": "~2.0.0-beta.1",
+    "codelyzer": "~2.0.0-beta.3",
-    "tslint": "^4.0.0",
+    "tslint": "4.1.1",
   },
   "dependencies": {
-    "@angular/common": "2.2.4",
-    "@angular/compiler": "2.2.4",
-    "@angular/core": "2.2.4",
-    "@angular/forms": "2.2.4",
-    "@angular/http": "2.2.4",
-    "@angular/platform-browser": "2.2.4",
-    "@angular/platform-browser-dynamic": "2.2.4",
-    "@angular/router": "3.2.4",
+    "@angular/common": "2.3.1",
+    "@angular/compiler": "2.3.1",
+    "@angular/core": "2.3.1",
+    "@angular/forms": "2.3.1",
+    "@angular/http": "2.3.1",
+    "@angular/platform-browser": "2.3.1",
+    "@angular/platform-browser-dynamic": "2.3.1",
+    "@angular/router": "3.3.1",
-    "rxjs": "5.0.0-beta.12",
+    "rxjs": "5.0.0-rc.4",
-    "zone.js": "0.6.23"
+    "zone.js": "0.7.2"
   }
 }
```

**Comment by fxck** [comment]
https://github.com/ngrx/store/issues/295

**Comment by karlhaas** [comment]
thx @fxck

**Comment by MikeRyanDev** [comment]
Looks like this has been fixed in v2.4.0 of Angular.

**Comment by juanlizarazo** [comment]
It is not fixed on angular 2.4.0 or 2.4.1 

At first I thought it would be too but after cleaning cache and removing node modules to get a clean dependency install:

npm clean cache
rm node_modules
npm install

Got the same issue. 

Error: No provider for Store!
with AOT compilation.

**Comment by bradseefeld** [comment]
@MikeRyan52, we are also running into this issue. Can you provide some clarification on what is needed to fix it when running 2.4.0+ or can we re-open the issue?

**Comment by bradseefeld** [comment]
Perhaps we can track in #307?

**Comment by brandonroberts** [comment]
This issue has been resolved with the latest 2.4.x release

**Comment by ishandutta2007** [comment]
These are my versions but I am still getting the error.
```
{
    "@angular/core": "~4.1.3",
    "@ngrx/store": "2.2.1"
}
```
Here are the stackoverflow questions for those:

https://stackoverflow.com/questions/44105335/no-provider-for-store-error-at-injectionerror/44105355#44105355

https://stackoverflow.com/questions/44114764/error-cant-resolve-all-parameters-for-store
